
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ananu
 */
public class Calculadora extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Calculadora.class.getName());
    private  DefaultTableModel modelo;
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        cambiarIcono();
        configurarTabla();
        
        
        DefaultComboBoxModel dcm = new DefaultComboBoxModel();
        
        for (UIManager.LookAndFeelInfo lfi : UIManager.getInstalledLookAndFeels())
          dcm.addElement(lfi.getName());
          jComboBoxLook.setModel(dcm);
    }
    
    public void configurarTabla(){
        
        modelo = (DefaultTableModel)TablaCalculos.getModel();
        
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(modelo);
        TablaCalculos.setRowSorter(sorter);
        
        List<RowSorter.SortKey> sortKeys = new ArrayList<>();
        sortKeys.add(new RowSorter.SortKey(3, SortOrder.DESCENDING));
        sortKeys.add(new RowSorter.SortKey(3, SortOrder.ASCENDING));

        
        
        sorter.setSortKeys(sortKeys);
        sorter.sort();
        
        TablaCalculos.getRowSorter().allRowsChanged();
    }
    
    public void cambiarIcono(){
        
        Image icono = new ImageIcon(getClass().getResource("/resources/icono.png")).getImage();
        setIconImage(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCalculos = new javax.swing.JTable();
        jComboBoxLook = new javax.swing.JComboBox<>();
        btnAñadir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TablaCalculos.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        TablaCalculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre Operación", "Primer número", "Segundo número", "Resultado"
            }
        ));
        jScrollPane1.setViewportView(TablaCalculos);

        jComboBoxLook.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxLook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLookActionPerformed(evt);
            }
        });

        btnAñadir.setText("Añadir operación");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar operación");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBoxLook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAñadir)
                        .addGap(16, 16, 16)
                        .addComponent(btnEliminar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jComboBoxLook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAñadir)
                    .addComponent(btnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxLookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLookActionPerformed
        
        try
     {
     UIManager.LookAndFeelInfo lookAndFeel = UIManager.getInstalledLookAndFeels()[jComboBoxLook.getSelectedIndex()];
     UIManager.setLookAndFeel(lookAndFeel.getClassName());
     SwingUtilities.updateComponentTreeUI(this);
     }
     catch (Throwable e)
     {
     }

    }//GEN-LAST:event_jComboBoxLookActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        
        Calculos calculos = new Calculos(this, true);
        calculos.setVisible(true);
        
        Calculo nuevoCalculo = calculos.getCalculo();
        modelo =(DefaultTableModel)TablaCalculos.getModel();
        modelo.addRow(new Object[]{
            nuevoCalculo.getNombreOp(),
            nuevoCalculo.getNumero1(),
            nuevoCalculo.getNumero2(),
            nuevoCalculo.getResultadoOp()
        });
        

    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        String nombreEliminar = JOptionPane.showInputDialog(this, "¿Qué operación desea eliminar? Introduzca resultado: ");
        
        if(nombreEliminar == null || nombreEliminar.isEmpty()){
            JOptionPane.showMessageDialog(this, "No se ha introducido ningún nombre.");
            return;
        }
        
        int resultadoEliminar;
    try {
        resultadoEliminar = Integer.parseInt(nombreEliminar.trim());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Debe introducir un número entero válido.");
        return;
    }

    modelo = (DefaultTableModel) TablaCalculos.getModel();

    boolean encontrado = false;

    // Recorrer las filas de abajo hacia arriba
    for (int i = modelo.getRowCount() - 1; i >= 0; i--) {
        // Suponiendo que el resultado está en la columna 0 (ajústalo si está en otra)
        int resultadoFila;
        try {
            resultadoFila = Integer.parseInt(modelo.getValueAt(i, 0).toString());
        } catch (NumberFormatException ex) {
            continue; // Si la celda no tiene número, la saltamos
        }

        if (resultadoEliminar == resultadoFila) {
            encontrado = true;
            int opcion = JOptionPane.showConfirmDialog(this, 
                "¿Está seguro de que desea eliminar la operación con resultado " + resultadoEliminar + "?",
                "Confirmar eliminación", 
                JOptionPane.YES_NO_OPTION);
            
            if (opcion == JOptionPane.YES_OPTION) {
                modelo.removeRow(i);
                JOptionPane.showMessageDialog(this, "Operación eliminada correctamente.");
            } else {
                JOptionPane.showMessageDialog(this, "No se ha eliminado la operación.");
            }
            break;
        }
    }

    if (!encontrado) {
        JOptionPane.showMessageDialog(this, "No se encontró ninguna operación con ese resultado.");
    }

    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Calculadora().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCalculos;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox<String> jComboBoxLook;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
